### ISSUE TITLE
output files are not created

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/atf2conll-convertor#4]
output :
```
epp@waga-masta:/alty/data/convert$ atf2conll-convertor -i '/alty/data/convert/cdli_atf_20180105.txt' 
epp@waga-masta:/alty/data/convert$ atf2conll-convertor -i /alty/data/convert/ 
Info: Converting the files  [####################################]  100%
```
but there is no output folder and no new files in my convert folder

**Comment by jayanthjaiswal** [comment]
The tool only processes ATF files, not text files. Just change the extension to '.atf' for the file and it will work. I explicitly made it so.

**Comment by epageperron** [comment]
perfect!
Now I get this :

```
epp@waga-masta:/alty/data/convert$ atf2conll-convertor -i /alty/data/convert/
Info: Converting the files  [####################################]  100%
Traceback (most recent call last):
  File "/usr/local/bin/atf2conll-convertor", line 11, in <module>
    load_entry_point('atf2conllconvertor==0.2.1', 'console_scripts', 'atf2conll-convertor')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/cli.py", line 37, in main
    check_and_process(pathname, verbose)
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/cli.py", line 23, in check_and_process
    file_process(pathname, verbose)
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/cli.py", line 13, in file_process
    convertor.convert()
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/convertor.py", line 44, in convert
    self.__parse(i, line.strip())
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/convertor.py", line 64, in __parse
    self.write2file()
  File "/usr/local/lib/python3.5/dist-packages/atf2conll_convertor/convertor.py", line 48, in write2file
    if len(IDlist) != len(set(IDlist)):
TypeError: object of type 'map' has no len()


```

**Comment by jayanthjaiswal** [comment]
Resolved with https://github.com/cdli-gh/atf2conll-convertor/commit/18a4cc78a738e62eff4e8d6517b80de730fde34c . Please test and close.
